services:
  # Backend Service
  - type: web
    name: school-system-backend
    runtime: node
    plan: free
    rootContext: backend
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECERET
        value: '#Manish#Project#Team'
      - key: CLOUDINARY_CLOUD_NAME
        value: dghffr4t1
      - key: CLOUDINARY_API_KEY
        value: 537171639812781
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://school-system-frontend-qbw5.onrender.com

  # Frontend Service
  - type: static
    name: school-system-frontend
    runtime: static
    plan: free
    rootContext: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://school-system-backend-qbw5.onrender.com

