services:
  # Backend Service
  - type: web
    name: school-system-backend
    runtime: docker
    plan: free
    dockerFilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false # Paste your mongodb+srv connection string in the dashboard
      - key: JWT_SECERET
        value: '#Manish#Project#Team'
      - key: CLOUDINARY_CLOUD_NAME
        value: dghffr4t1
      - key: CLOUDINARY_API_KEY
        value: 537171639812781
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: school-system-frontend
          property: host

  # Frontend Service
  - type: web
    name: school-system-frontend
    runtime: docker
    plan: free
    dockerFilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: school-system-backend
          property: host